#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Guru Ubuntu Installer ISO - Jei Mchfundi" {
        set isofile="/boot/iso/ubuntu.iso"
        loopback loop (hd0,1)$isofile
        linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile noprompt noeject
        initrd (loop)/casper/initrd
}


menuentry "Guru Linux Installer ISO - Jei Mchfundi" {
        set isofile="/boot/iso/linux.iso"
        loopback loop (hd0,1)$isofile
        linux (loop)/live/vmlinuz boot=casper iso-scan/filename=$isofile noprompt noeject
        initrd (loop)/live/initrd.img
}

menuentry 'Guru Windows Installer Partition - Jei Mchfundi' {
	set root=(hd0,3)
	insmod part_msdos
	insmod	ntfs
	insmod	ntldr
	drivemap -s (hd0)${root}
	ntldr /bootmgr
}
